version: '3'
services:
  web_macromonkeys_tri3:
    env_file:
      - .env
    image: macromonkeys_tri3
    build: .
    ports:
      - "8298:8085"
    volumes:
      - persistent_volume:/app/volumes
    restart: unless-stopped
volumes:
  persistent_volume:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/ubuntu/tri3_monkey_8298/volumes
