name: Deploy to Server
on: [push]
jobs:
  AWS-Deploy:
    if: ${{ false }}  # disable for now
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ secrets.SSH_KEY }} | base64 -d > key.pem
      - run: chmod 400 key.pem
      - run: ssh -i key.pem -o StrictHostKeyChecking=no ubuntu@34.205.167.218 'cd ~/tri3_monkey_8298/; git pull; docker-compose down; docker-compose up -d --build'
